"""Expected data structure for BoxScoreSummaryV3 endpoint."""

_EXPECTED_DATA = {
    "GameSummary": [
        "gameId",
        "gameCode",
        "gameStatus",
        "gameStatusText",
        "period",
        "gameClock",
        "gameTimeUTC",
        "gameEt",
        "awayTeamId",
        "homeTeamId",
        "duration",
        "attendance",
        "sellout",
    ],
    "GameInfo": [
        "gameId",
        "gameDate",
        "attendance",
        "gameDuration",
    ],
    "ArenaInfo": [
        "gameId",
        "arenaId",
        "arenaName",
        "arenaCity",
        "arenaState",
        "arenaCountry",
        "arenaTimezone",
    ],
    "Officials": [
        "gameId",
        "personId",
        "name",
        "nameI",
        "firstName",
        "familyName",
        "jerseyNum",
    ],
    "LineScore": [
        "gameId",
        "teamId",
        "teamCity",
        "teamName",
        "teamTricode",
        "teamSlug",
        "teamWins",
        "teamLosses",
        "period1Score",
        "period2Score",
        "period3Score",
        "period4Score",
        "score",
    ],
    "InactivePlayers": [
        "gameId",
        "teamId",
        "personId",
        "firstName",
        "familyName",
        "jerseyNum",
    ],
    "LastFiveMeetings": [
        "recencyOrder",
        "gameId",
        "gameTimeUTC",
        "gameEt",
        "gameStatus",
        "gameStatusText",
        "awayTeamId",
        "awayTeamCity",
        "awayTeamName",
        "awayTeamTricode",
        "awayTeamScore",
        "awayTeamWins",
        "awayTeamLosses",
        "homeTeamId",
        "homeTeamCity",
        "homeTeamName",
        "homeTeamTricode",
        "homeTeamScore",
        "homeTeamWins",
        "homeTeamLosses",
    ],
    "OtherStats": [
        "gameId",
        "teamId",
        "teamCity",
        "teamName",
        "teamTricode",
        "points",
        "reboundsTotal",
        "assists",
        "steals",
        "blocks",
        "turnovers",
        "fieldGoalsPercentage",
        "threePointersPercentage",
        "freeThrowsPercentage",
        "pointsInThePaint",
        "pointsSecondChance",
        "pointsFastBreak",
        "biggestLead",
        "leadChanges",
        "timesTied",
        "biggestScoringRun",
        "turnoversTeam",
        "turnoversTotal",
        "reboundsTeam",
        "pointsFromTurnovers",
        "benchPoints",
    ],
    "AvailableVideo": [
        "gameId",
        "videoAvailableFlag",
        "ptAvailable",
        "ptXYZAvailable",
        "whStatus",
        "hustleStatus",
        "historicalStatus",
    ],
}
