"""Expected data structure for ScoreboardV3 endpoint."""

_EXPECTED_DATA = {
    "ScoreboardInfo": [
        "gameDate",
        "leagueId",
        "leagueName",
    ],
    "GameHeader": [
        "gameId",
        "gameCode",
        "gameStatus",
        "gameStatusText",
        "period",
        "gameClock",
        "gameTimeUTC",
        "gameEt",
        "regulationPeriods",
        "seriesGameNumber",
        "gameLabel",
        "gameSubLabel",
        "seriesText",
        "ifNecessary",
        "seriesConference",
        "poRoundDesc",
        "gameSubtype",
        "isNeutral",
    ],
    "LineScore": [
        "gameId",
        "teamId",
        "teamCity",
        "teamName",
        "teamTricode",
        "teamSlug",
        "wins",
        "losses",
        "score",
        "seed",
        "inBonus",
        "timeoutsRemaining",
    ],
    "GameLeaders": [
        "gameId",
        "teamId",
        "leaderType",
        "personId",
        "name",
        "playerSlug",
        "jerseyNum",
        "position",
        "teamTricode",
        "points",
        "rebounds",
        "assists",
    ],
    "TeamLeaders": [
        "gameId",
        "teamId",
        "leaderType",
        "personId",
        "name",
        "playerSlug",
        "jerseyNum",
        "position",
        "teamTricode",
        "points",
        "rebounds",
        "assists",
        "seasonLeadersFlag",
    ],
    "Broadcasters": [
        "gameId",
        "broadcasterType",
        "broadcasterId",
        "broadcastDisplay",
        "broadcasterTeamId",
        "broadcasterDescription",
    ],
}
